version: '3.8'

services:
  mysql-db:
    image: mysql
    
    container_name: mysql_teste
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contas
      MYSQL_USER: root 
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3310:3306"
    cap_add:
      - SYS_NICE
  adminer:
    image: adminer:4
    container_name: adminer_teste
    ports:
      - 8080:8080