# Generated by Django 4.0.4 on 2022-04-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_transacao_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(verbose_name='%Y-%m-%d'),
        ),
    ]
