# Generated by Django 4.0.4 on 2022-04-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0010_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.FloatField(),
        ),
    ]
