# Generated by Django 4.0.4 on 2022-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_alter_transacao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
